### ISSUE TITLE
Bump wavelink version from v1.3.5 to v2.0.1

### ISSUE THREAD

**Issue by andrewyazura** [sasunday26/discord-music-bot#10]
We're currently using an outdated version of `wavelink` library. I propose updating it to the new release, v2.0.1.

It adds a couple of neat features like AutoPlay, looping and fetching YouTube thumbnails.

Updated task list:
- [x] Bump `wavelink` version to v2.0.1
- [x] Bump `lavalink` version to v3.7.5
- [x] Move to `discord.py`

This issue blocks #9 and has a higher priority over it

**Comment by andrewyazura** [comment]
@yaroslavpashynskyi and @orehzzz, divide the tasks between each other and fix ASAP

**Comment by yaroslavpashynskyi** [comment]
🥵

**Comment by andrewyazura** [comment]
Forgot to add a link to the new release: https://github.com/PythonistaGuild/Wavelink/releases/tag/v2.0.1

**Comment by andrewyazura** [comment]
I'm going to do it myself because there is a huge fucking problem with `discord-py` and `py-cord` packages conflicting after the `wavelink` update

**Comment by andrewyazura** [comment]
`wavelink` authors made `discord.py` their direct dependency (https://github.com/PythonistaGuild/Wavelink/commit/b2023a0fb4ed1f086a36936ba65fdaa1bfadb5d2), so you can't even import `pycord` now. And even if you could import it, it would be no use as they are probably incompatible now

**Comment by andrewyazura** [comment]
Updated task list:
- [ ] Bump `wavelink` version to v2.0.1
- [ ] Bump `lavalink` version to v3.7.5
- [ ] Move to `discord.py`
- [ ] Add /loop command
- [ ] Add /autoplay command
- [ ] If possible, display YouTube thumbnails in /now_playing

**Comment by andrewyazura** [comment]
`discord.py` is a fucking piece of shit, I just can't understand how anyone could make adding slash commands so bad. In `pycord`, you just add a decorator, and it's done, like this:

```python
@discord.slash_command(name="volume", description="set audio volume")
@discord.option(
    "volume",
    int,
    min_value=0,
    max_value=1000,
    description="percentage from 0 to 1000",
)
```

But no, in `discord.py` you must define a fucking tree of commands and then synchronize it. It's ridiculous that you have to go through all of that, and it still works like shit.

Honestly, I'd much rather move the bot to JavaScript, than to `discord.py`. I'll be looking for ways to make `wavelink==2.0` work with `pycord`, or replace `wavelink` all together.

**Comment by yaroslavpashynskyi** [comment]
Maybe try nextcord, I've seen some forks on wavelink repo where discord.py replaced with nextcord.

**Comment by andrewyazura** [comment]
`nextcord` seems like a nice option, but I would rather not spend any more time trying to migrate bot to another framework, so I'll fork `wavelink` and replace `discord.py` with `wavelink`

**Comment by andrewyazura** [comment]
fucking hell, looks like we'll have to move to `discord.py` because `wavelink` depends on it too much to change anything

**Comment by andrewyazura** [comment]
With a can of Red Bull and a sleepless night, I successfully transferred the bot to `discord.py`. There is a problem with Spotify track playback, but that is probably something on `wavelink`'s side.

Also, I found a possible bug in `wavelink`, I'm going to make a fork and try fixing it

**Comment by andrewyazura** [comment]
So, I made a fork and fixed the bug, but we have to wait for the fix to be released. I made a separate issue for that: #12

**Comment by andrewyazura** [comment]
Another issue, when playing Spotify album, there is a `KeyError`:

```python
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.11/site-packages/wavelink/ext/spotify/__init__.py", line 156, in __anext__
    track = SpotifyTrack(track)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wavelink/ext/spotify/__init__.py", line 227, in __init__
    self.isrc: str | None = data["external_ids"].get("isrc")
                            ~~~~^^^^^^^^^^^^^^^^
KeyError: 'external_ids'
```

Respective issue already exists: https://github.com/PythonistaGuild/Wavelink/issues/209
I made a PR with a possible fix: https://github.com/PythonistaGuild/Wavelink/pull/212

**Comment by andrewyazura** [comment]
Anyway, the bot is working properly on this version, so I suppose I'll just merge it into `main` and add new issues for `/loop`, `/autoplay` and YouTube thumbnail features

**Comment by andrewyazura** [comment]
I created a PR, this issue is no longer needed
